// artifact-pipeline demonstrates the full artifact lifecycle with a tern server:
//  1. Upload a local file as a user artifact.
//  2. Retrieve its content and send it to a coding agent with a generation prompt.
//  3. List the files generated by the agent in the session and download one.
//
// Prerequisites:
//   - A running tern server (e.g., via examples/minimal-server)
//   - A configured coding agent (default: wayfinder)
//
// Usage:
//
//	go run . [options]
//
// Examples:
//
//	# Upload input.txt, ask wayfinder to generate output.txt, then download it
//	go run . --input input.txt --key inputs/template.txt --output-key output.txt
//
//	# Use claudecode agent on a remote server
//	go run . --server http://192.168.1.100:3100 --agent claudecode --input data.csv
//
//	# Run with built binary
//	./bin/artifact-pipeline --input input.txt
package main

import (
	"context"
	"flag"
	"fmt"
	"io"
	"log"
	"os"
	"path/filepath"
	"strings"

	client "github.com/axsh/arctic-tern/client/v1"
)

func main() {
	serverURL := flag.String("server", "http://localhost:3100", "Tern server URL")
	agent := flag.String("agent", "wayfinder", "Coding agent name")
	model := flag.String("model", "", "Model name (empty = server default)")
	inputPath := flag.String("input", "input.txt", "Local file to upload as user artifact")
	artifactKey := flag.String("key", "inputs/template.txt", "Logical key for the user artifact")
	outputKey := flag.String("output-key", "", "Key of the system artifact to download (empty = first created file)")
	savePath := flag.String("save", "./output.txt", "Local path to save the downloaded file")
	workDir := flag.String("work-dir", ".", "Working directory for the coding agent session")
	flag.Parse()

	ctx := context.Background()
	c := client.New(*serverURL, client.WithNoTimeout())

	if err := runUpload(ctx, c, *inputPath, *artifactKey); err != nil {
		log.Fatalf("[Step 1] upload failed: %v", err)
	}

	sessionID, err := runGenerate(ctx, c, *artifactKey, *agent, *model, *workDir)
	if err != nil {
		log.Fatalf("[Step 2] generate failed: %v", err)
	}

	if err := runDownload(ctx, c, sessionID, *outputKey, *savePath); err != nil {
		log.Fatalf("[Step 3] download failed: %v", err)
	}
}

// runUpload uploads the local file at localPath to the server under the logical key.
func runUpload(ctx context.Context, c *client.Client, localPath, key string) error {
	resp, err := c.UserArtifacts().PutFile(ctx, key, localPath)
	if err != nil {
		return err
	}
	fmt.Printf("[Step 1] Uploaded: %s (%d bytes, sha256: %s, status: %s)\n",
		resp.Key, resp.Size, resp.SHA, resp.Status)
	return nil
}

// runGenerate fetches the artifact, writes it to a file in workDir so the coding
// agent can read it via its file-access tools, sends a generation prompt, streams
// the response, and returns the session ID for subsequent artifact retrieval.
func runGenerate(ctx context.Context, c *client.Client, key, agentName, model, workDir string) (string, error) {
	rc, err := c.UserArtifacts().Download(ctx, key)
	if err != nil {
		return "", fmt.Errorf("download artifact %q: %w", key, err)
	}
	defer rc.Close()
	content, err := io.ReadAll(rc)
	if err != nil {
		return "", fmt.Errorf("read artifact content: %w", err)
	}
	fmt.Printf("[Step 2] Artifact content fetched: %d bytes\n", len(content))

	// Write the artifact as a file so the agent can read it through its file tools.
	// This avoids any prompt-encoding issues with the content.
	inputFile := "artifact_input.txt"
	inputPath := filepath.Join(workDir, inputFile)
	if err := os.MkdirAll(workDir, 0o755); err != nil {
		return "", fmt.Errorf("create work dir: %w", err)
	}
	if err := os.WriteFile(inputPath, content, 0o644); err != nil {
		return "", fmt.Errorf("write artifact to work dir: %w", err)
	}
	fmt.Printf("[Step 2] Artifact written to: %s\n", inputPath)

	// Default collectors: structured_tool + shell_parser ON, workdir_reconcile OFF.
	// Set FileChangeCollectors.WorkdirReconcile to enable git/snapshot supplement if needed.
	session, err := c.CreateSession(ctx, client.SessionRequest{
		Agent:   agentName,
		Model:   model,
		WorkDir: workDir,
	})
	if err != nil {
		return "", fmt.Errorf("create session: %w", err)
	}
	defer session.Terminate(ctx)
	fmt.Printf("[Step 2] Session created: %s\n", session.ID)

	prompt := fmt.Sprintf(
		"Read the file %q in the current directory, then create a new file called output.txt that summarizes the key points.",
		inputFile)

	stream, err := session.SendText(ctx, prompt)
	if err != nil {
		return "", fmt.Errorf("send message: %w", err)
	}
	fmt.Println("[Step 2] Agent response:")
	if err := stream.Output(os.Stdout); err != nil {
		return "", fmt.Errorf("stream output: %w", err)
	}

	return session.ID, nil
}

// runDownload lists the files generated by the agent in the given session and
// downloads the target key (or the first created file if outputKey is empty).
func runDownload(ctx context.Context, c *client.Client, sessionID, outputKey, savePath string) error {
	page, err := c.SystemArtifacts().List(ctx, client.SystemArtifactFilter{
		SessionIDs: []string{sessionID},
		Operation:  "create",
	})
	if err != nil {
		return fmt.Errorf("list system artifacts: %w", err)
	}
	fmt.Printf("[Step 3] Generated files in session %s (%d total):\n", sessionID, page.TotalCount)
	for _, item := range page.Items {
		fmt.Printf("  %s  (%s)\n", item.Key, item.Operation)
	}

	target := outputKey
	if target == "" {
		if len(page.Items) == 0 {
			return fmt.Errorf("no generated files found in session %s", sessionID)
		}
		target = page.Items[0].Key
	}

	// Resolve output-key by basename when an exact key match is not present
	// (system artifact keys may be absolute paths with mixed separators).
	downloadKey := target
	found := false
	for _, item := range page.Items {
		if item.Key == target {
			downloadKey = item.Key
			found = true
			break
		}
	}
	if !found {
		for _, item := range page.Items {
			if filepath.Base(item.Key) == filepath.Base(target) {
				downloadKey = item.Key
				found = true
				break
			}
		}
	}
	if !found {
		return fmt.Errorf("artifact %q not found in session %s (available: %d files)", target, sessionID, len(page.Items))
	}

	rc, err := c.SystemArtifacts().Download(ctx, downloadKey)
	if err != nil {
		return fmt.Errorf("download %q: %w", downloadKey, err)
	}
	defer rc.Close()

	data, err := io.ReadAll(rc)
	if err != nil {
		return fmt.Errorf("read downloaded content: %w", err)
	}

	if savePath == "" {
		parts := strings.Split(target, "/")
		savePath = "./" + parts[len(parts)-1]
	}

	if err := os.WriteFile(savePath, data, 0o644); err != nil {
		return fmt.Errorf("write file %q: %w", savePath, err)
	}
	fmt.Printf("[Step 3] Downloaded: %s -> %s (%d bytes)\n", downloadKey, savePath, len(data))
	return nil
}
